// 20220926150513
// https://dev.elevator.umn.edu/defaultinstance/assetManager/getTemplate/68

import { Template } from "@/types";

const mockTemplate: Template = {
  templateId: "68",
  templateName: "All Fields Test",
  widgetArray: [
    {
      widgetId: 3418,
      type: "text",
      allowMultiple: true,
      attemptAutocomplete: false,
      fieldTitle: "title_1",
      label: "Title",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: true,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: true,
      clickToSearchType: 1,
      viewOrder: 1,
      templateOrder: 1,
    },
    {
      widgetId: 3419,
      type: "checkbox",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "coolstuff_1",
      label: "Cool Stuff",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 1,
      viewOrder: 2,
      templateOrder: 2,
    },
    {
      widgetId: 3420,
      type: "date",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "creation_1",
      label: "Creation",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 1,
      viewOrder: 3,
      templateOrder: 3,
    },
    {
      widgetId: 3421,
      type: "location",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "location_1",
      label: "Location",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 1,
      viewOrder: 4,
      templateOrder: 4,
    },
    {
      widgetId: 3422,
      type: "multiselect",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "cascadeselect_1",
      label: "Cascade Select",
      tooltip: "",
      fieldData: {
        country: {
          usa: {
            state: {
              minnesota: {
                city: {
                  mankato: {
                    neighborhood: ["campus", "downtown"],
                  },
                  minneapolis: {
                    neighborhood: ["uptown", "downtown"],
                  },
                },
              },
              wisconsin: {
                city: ["madison", "milwaukee"],
              },
            },
          },
          canada: {
            state: {
              quebec: {
                city: ["montreal"],
              },
              alberta: {
                city: ["fakeville", "faketown"],
              },
            },
          },
        },
      },
      display: true,
      displayInPreview: false,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: true,
      clickToSearchType: 1,
      viewOrder: 5,
      templateOrder: 5,
    },
    {
      widgetId: 3423,
      type: "related asset",
      allowMultiple: true,
      attemptAutocomplete: false,
      fieldTitle: "relatedstuff_1",
      label: "Related Stuff",
      tooltip: "",
      fieldData: {
        nestData: true,
        showLabel: true,
        matchAgainst: [0],
        displayInline: false,
        thumbnailView: false,
        defaultTemplate: 0,
        ignoreForDateSearch: false,
        ignoreForDigitalAsset: false,
        collapseNestedChildren: false,
        ignoreForLocationSearch: false,
      },
      display: true,
      displayInPreview: true,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 1,
      viewOrder: 6,
      templateOrder: 6,
    },
    {
      widgetId: 3424,
      type: "select",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "globalsearch_1",
      label: "Global Search",
      tooltip: "",
      fieldData: {
        multiSelect: false,
        selectGroup: ["option 1", "option 2", "option 3"],
      },
      display: true,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: true,
      clickToSearchType: 0,
      viewOrder: 7,
      templateOrder: 7,
    },
    {
      widgetId: 3425,
      type: "tag list",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "sometags_1",
      label: "Some tags",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 1,
      viewOrder: 8,
      templateOrder: 8,
    },
    {
      widgetId: 3426,
      type: "text area",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "bigtext_1",
      label: "Big Text",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 1,
      viewOrder: 9,
      templateOrder: 9,
    },
    {
      widgetId: 3427,
      type: "upload",
      allowMultiple: true,
      attemptAutocomplete: false,
      fieldTitle: "image_1",
      label: "Image",
      tooltip: "",
      fieldData: {
        extractDate: true,
        forceTiling: false,
        enableDendro: false,
        enableIframe: false,
        enableTiling: true,
        extractLocation: true,
        enableAnnotation: false,
        interactiveTranscript: false,
      },
      display: true,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 1,
      viewOrder: 10,
      templateOrder: 10,
    },
    {
      widgetId: 3428,
      type: "related asset",
      allowMultiple: true,
      attemptAutocomplete: false,
      fieldTitle: "collapsedjoinrecord_1",
      label: "Collapsed Join Record",
      tooltip: "",
      fieldData: {
        nestData: true,
        showLabel: true,
        matchAgainst: [72],
        displayInline: true,
        thumbnailView: false,
        defaultTemplate: 72,
        ignoreForDateSearch: false,
        ignoreForDigitalAsset: false,
        collapseNestedChildren: false,
        ignoreForLocationSearch: false,
      },
      display: true,
      displayInPreview: true,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 1,
      viewOrder: 11,
      templateOrder: 11,
    },
  ],
  collections: {
    "20": "Collection two",
    "24": "Language Center",
    "25": {
      "Blank Generation": {
        "23": "Test Collection - Don't use",
        "28": {
          fades: {
            "1": "Initial Collection",
          },
        },
      },
    },
    "26": "Lang Center New",
    "27": "Don't use - Really Blank but Also Really LongReally Blank but Also Really Long",
    "29": "Date testing - Don't use",
    "35": "Obama Speeches",
    "40": "new test collection - don't use",
    "41": "Speeches 2 - Don't use",
    "42": "Tree Cores",
    "71": "GeoTime Test",
    "72": "Research Paper 1",
    "74": {
      "API Import": {
        "75": "Bennington Test Collection",
      },
    },
    "78": "blarg",
    "79": "Related Asset Testing",
  },
  allowedCollections: [],
};

export default mockTemplate;
