// 20220901084317
// https://dev.elevator.umn.edu/dcl/assetManager/getTemplate/26

import { Template } from "@/types";

const mockTemplate: Template = {
  templateId: "26",
  templateName: "Old DCL Works",
  widgetArray: [
    {
      widgetId: 2247,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "workid_7",
      label: "Work Id",
      tooltip: "",
      fieldData: [],
      display: false,
      displayInPreview: false,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 0,
      viewOrder: 1,
      templateOrder: 17,
    },
    {
      widgetId: 2258,
      type: "related asset",
      allowMultiple: true,
      attemptAutocomplete: true,
      fieldTitle: "worktitle_7",
      label: "Work Title",
      tooltip: "",
      fieldData: {
        nestData: true,
        showLabel: true,
        displayInline: true,
        thumbnailView: false,
        defaultTemplate: 19,
        collapseNestedChildren: false,
      },
      display: true,
      displayInPreview: true,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 0,
      viewOrder: 2,
      templateOrder: 18,
    },
    {
      widgetId: 2257,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "comments_7",
      label: "Comments",
      tooltip: "",
      fieldData: [],
      display: false,
      displayInPreview: false,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 0,
      viewOrder: 3,
      templateOrder: 19,
    },
    {
      widgetId: 2260,
      type: "related asset",
      allowMultiple: true,
      attemptAutocomplete: true,
      fieldTitle: "creator_7",
      label: "Creator",
      tooltip: "",
      fieldData: {
        nestData: true,
        showLabel: true,
        displayInline: true,
        thumbnailView: false,
        defaultTemplate: 24,
        collapseNestedChildren: false,
      },
      display: true,
      displayInPreview: true,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 0,
      viewOrder: 4,
      templateOrder: 20,
    },
    {
      widgetId: 2259,
      type: "related asset",
      allowMultiple: true,
      attemptAutocomplete: true,
      fieldTitle: "datelocation_7",
      label: "Date/Location",
      tooltip: "",
      fieldData: {
        nestData: true,
        showLabel: true,
        displayInline: true,
        thumbnailView: false,
        defaultTemplate: 20,
        collapseNestedChildren: false,
      },
      display: true,
      displayInPreview: true,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 0,
      viewOrder: 5,
      templateOrder: 21,
    },
    {
      widgetId: 2248,
      type: "text",
      allowMultiple: true,
      attemptAutocomplete: true,
      fieldTitle: "styleperiod_7",
      label: "Style Period",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 0,
      viewOrder: 6,
      templateOrder: 22,
    },
    {
      widgetId: 2250,
      type: "text",
      allowMultiple: true,
      attemptAutocomplete: true,
      fieldTitle: "culture_7",
      label: "Culture",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 0,
      viewOrder: 7,
      templateOrder: 23,
    },
    {
      widgetId: 2253,
      type: "text",
      allowMultiple: true,
      attemptAutocomplete: false,
      fieldTitle: "language_7",
      label: "Language",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 0,
      viewOrder: 8,
      templateOrder: 24,
    },
    {
      widgetId: 2262,
      type: "related asset",
      allowMultiple: true,
      attemptAutocomplete: false,
      fieldTitle: "workmeasurement_7",
      label: "Work Measurement",
      tooltip: "",
      fieldData: {
        nestData: true,
        showLabel: true,
        displayInline: true,
        thumbnailView: false,
        defaultTemplate: 21,
        collapseNestedChildren: false,
      },
      display: true,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 0,
      viewOrder: 9,
      templateOrder: 25,
    },
    {
      widgetId: 2249,
      type: "text",
      allowMultiple: true,
      attemptAutocomplete: true,
      fieldTitle: "classification_7",
      label: "Classification",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: true,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 0,
      viewOrder: 10,
      templateOrder: 26,
    },
    {
      widgetId: 2261,
      type: "related asset",
      allowMultiple: true,
      attemptAutocomplete: true,
      fieldTitle: "views_7",
      label: "Views",
      tooltip: "",
      fieldData: {
        nestData: true,
        showLabel: true,
        displayInline: false,
        thumbnailView: true,
        defaultTemplate: 25,
        collapseNestedChildren: false,
      },
      display: true,
      displayInPreview: false,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 0,
      viewOrder: 16,
      templateOrder: 27,
    },
    {
      widgetId: 2251,
      type: "text",
      allowMultiple: true,
      attemptAutocomplete: true,
      fieldTitle: "technique_7",
      label: "Technique",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 0,
      viewOrder: 11,
      templateOrder: 28,
    },
    {
      widgetId: 2252,
      type: "text",
      allowMultiple: true,
      attemptAutocomplete: false,
      fieldTitle: "materials_7",
      label: "Materials",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 0,
      viewOrder: 12,
      templateOrder: 29,
    },
    {
      widgetId: 2254,
      type: "text",
      allowMultiple: true,
      attemptAutocomplete: false,
      fieldTitle: "stateedition_7",
      label: "State Edition",
      tooltip: "",
      fieldData: [],
      display: false,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 0,
      viewOrder: 13,
      templateOrder: 30,
    },
    {
      widgetId: 2255,
      type: "text",
      allowMultiple: true,
      attemptAutocomplete: false,
      fieldTitle: "inscription_7",
      label: "Inscription",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 0,
      viewOrder: 14,
      templateOrder: 31,
    },
    {
      widgetId: 2256,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "repositoryobjectid_7",
      label: "Repository Object ID",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: 0,
      viewOrder: 15,
      templateOrder: 32,
    },
  ],
  collections: {
    "16": "Asian Languages and Literatures, Dept. of",
    "19": "Metropolitan Design Center",
    "21": "Cultural Studies & Comparative Literature",
    "22": "Practice Collection",
    "43": "Apple",
    "44": "Banana",
    "45": "Coconut",
    "46": "Date",
    "47": "Eaglenuts",
    "48": "Fresh pears",
    "49": "Grapes",
    "50": "Holly",
    "51": "Iodine",
    "52": "Jackfruit",
    "53": "Krush",
    "54": "Lemon",
    "55": "Monkey",
    "56": "Not the best",
    "57": "Options",
    "58": "Pandas",
    "59": "Questions",
    "60": "Resources",
    "61": "Very",
    "62": "Tom",
    "63": "Unlimited",
    "64": "Why",
    "65": "Xactly",
    "66": "Yup",
    "67": "Zebra",
    "68": "Aston",
    "69": "Eagle",
    "70": "Dude",
    "73": "Working Collection",
    "74": {
      "API Import": {
        "75": "Bennington Test Collection",
      },
    },
  },
  allowedCollections: [],
};

export default mockTemplate;
