// 20220901084416
// https://dev.elevator.umn.edu/dcl/assetManager/getTemplate/25

export default {
  templateId: "25",
  templateName: "Old DCL Views",
  widgetArray: [
    {
      widgetId: 1547,
      type: "tag list",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "newkeywords_7",
      label: "New Keywords",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 27,
      templateOrder: 27,
    },
    {
      widgetId: 1525,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "digitalid_7",
      label: "Digital ID",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: true,
      required: false,
      searchable: true,
      directSearch: true,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 1,
      templateOrder: 27,
    },
    {
      widgetId: 1546,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "copyrightfullvideo_7",
      label: "Copyright Full Video",
      tooltip: "",
      fieldData: [],
      display: false,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 26,
      templateOrder: 28,
    },
    {
      widgetId: 1536,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "title_7",
      label: "Title",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: true,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 2,
      templateOrder: 29,
    },
    {
      widgetId: 1537,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "viewtype_7",
      label: "View Type",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: true,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 4,
      templateOrder: 30,
    },
    {
      widgetId: 1535,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "subtype_7",
      label: "Sub Type",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 5,
      templateOrder: 31,
    },
    {
      widgetId: 1528,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "folionumber_7",
      label: "Folio Number",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 3,
      templateOrder: 32,
    },
    {
      widgetId: 1524,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "description_7",
      label: "Description",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 6,
      templateOrder: 33,
    },
    {
      widgetId: 1521,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "alttype_7",
      label: "Alt Type",
      tooltip: "",
      fieldData: [],
      display: false,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 7,
      templateOrder: 34,
    },
    {
      widgetId: 1529,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "keywords_7",
      label: "Keywords",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: true,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 8,
      templateOrder: 35,
    },
    {
      widgetId: 1539,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "viewagentid_7",
      label: "View Agent Id",
      tooltip: "",
      fieldData: [],
      display: false,
      displayInPreview: false,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 11,
      templateOrder: 36,
    },
    {
      widgetId: 1543,
      type: "related asset",
      allowMultiple: true,
      attemptAutocomplete: false,
      fieldTitle: "agent_7",
      label: "Agent",
      tooltip: "",
      fieldData: {
        nestData: true,
        showLabel: true,
        displayInline: false,
        thumbnailView: false,
        defaultTemplate: 18,
        collapseNestedChildren: false,
      },
      display: true,
      displayInPreview: true,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 9,
      templateOrder: 37,
    },
    {
      widgetId: 1538,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "viewagentextent_7",
      label: "View Agent Extent",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: true,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 10,
      templateOrder: 38,
    },
    {
      widgetId: 1523,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "date_7",
      label: "Date",
      tooltip: "",
      fieldData: [],
      display: false,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 12,
      templateOrder: 39,
    },
    {
      widgetId: 1531,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "orderid_7",
      label: "Order Id",
      tooltip: "",
      fieldData: [],
      display: false,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 13,
      templateOrder: 40,
    },
    {
      widgetId: 1545,
      type: "related asset",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "ordersource_7",
      label: "Order/Source",
      tooltip: "",
      fieldData: {
        nestData: true,
        showLabel: true,
        displayInline: true,
        thumbnailView: false,
        defaultTemplate: 23,
        collapseNestedChildren: false,
      },
      display: true,
      displayInPreview: true,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 14,
      templateOrder: 41,
    },
    {
      widgetId: 1532,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "pagenumber_7",
      label: "Page Number",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 15,
      templateOrder: 42,
    },
    {
      widgetId: 1527,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "figurenumber_7",
      label: "Figure Number",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 16,
      templateOrder: 43,
    },
    {
      widgetId: 1533,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "publiccopyright_7",
      label: "Public Copyright",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: true,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 17,
      templateOrder: 44,
    },
    {
      widgetId: 1544,
      type: "upload",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "file_7",
      label: "File",
      tooltip: "",
      fieldData: {
        extractDate: false,
        extractLocation: false,
      },
      display: true,
      displayInPreview: true,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 18,
      templateOrder: 45,
    },
    {
      widgetId: 1530,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "mediatype_7",
      label: "Media Type",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 19,
      templateOrder: 46,
    },
    {
      widgetId: 1522,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "classification_7",
      label: "Classification",
      tooltip: "",
      fieldData: [],
      display: false,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 20,
      templateOrder: 47,
    },
    {
      widgetId: 1534,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "scale_7",
      label: "Scale",
      tooltip: "",
      fieldData: [],
      display: true,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 21,
      templateOrder: 48,
    },
    {
      widgetId: 1542,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "legacyid_7",
      label: "Legacy Id",
      tooltip: "",
      fieldData: [],
      display: false,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 25,
      templateOrder: 49,
    },
    {
      widgetId: 1540,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "viewid_7",
      label: "View Id",
      tooltip: "",
      fieldData: [],
      display: false,
      displayInPreview: false,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 22,
      templateOrder: 50,
    },
    {
      widgetId: 1541,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "workid_7",
      label: "Work Id",
      tooltip: "",
      fieldData: [],
      display: false,
      displayInPreview: false,
      required: false,
      searchable: true,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 23,
      templateOrder: 51,
    },
    {
      widgetId: 1526,
      type: "text",
      allowMultiple: false,
      attemptAutocomplete: false,
      fieldTitle: "digitized_7",
      label: "digitized",
      tooltip: "",
      fieldData: [],
      display: false,
      displayInPreview: false,
      required: false,
      searchable: false,
      directSearch: false,
      clickToSearch: false,
      clickToSearchType: null,
      viewOrder: 24,
      templateOrder: 52,
    },
  ],
  collections: {
    "16": "Asian Languages and Literatures, Dept. of",
    "19": "Metropolitan Design Center",
    "21": "Cultural Studies & Comparative Literature",
    "22": "Practice Collection",
    "43": "Apple",
    "44": "Banana",
    "45": "Coconut",
    "46": "Date",
    "47": "Eaglenuts",
    "48": "Fresh pears",
    "49": "Grapes",
    "50": "Holly",
    "51": "Iodine",
    "52": "Jackfruit",
    "53": "Krush",
    "54": "Lemon",
    "55": "Monkey",
    "56": "Not the best",
    "57": "Options",
    "58": "Pandas",
    "59": "Questions",
    "60": "Resources",
    "61": "Very",
    "62": "Tom",
    "63": "Unlimited",
    "64": "Why",
    "65": "Xactly",
    "66": "Yup",
    "67": "Zebra",
    "68": "Aston",
    "69": "Eagle",
    "70": "Dude",
    "73": "Working Collection",
    "74": {
      "API Import": {
        "75": "Bennington Test Collection",
      },
    },
  },
  allowedCollections: [],
};
